// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"authentication/pkg/api"
	"authentication/pkg/client"
	"authentication/pkg/config"
	"authentication/pkg/db"
	"authentication/pkg/repository"
	"authentication/pkg/usecase"
)

// Injectors from wire.go:

func InitializeServices(cfg *config.Config) (*api.RpcServer, error) {
	stripeConfig, err := ProvideStripeConfig()
	if err != nil {
		return nil, err
	}
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	adminRepository := repository.NewAdminRepo(gormDB)
	adminUsecase := usecase.NewAdminUsecase(adminRepository)
	paymentRepo := repository.NewPaymentRepo(gormDB, stripeConfig)
	paymentUsecase := usecase.NewPaymentUsecase(paymentRepo)
	authUserService := client.NewUserService(userUseCase, adminUsecase, paymentUsecase)
	rpcServer := api.NewRPCServer(stripeConfig, cfg, authUserService)
	return rpcServer, nil
}

// wire.go:

func ProvideStripeConfig() (*config.StripeConfig, error) {
	return config.NewStripeConfig()
}
