// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"problem-service/pkg/client"
	"problem-service/pkg/config"
	"problem-service/pkg/db"
	"problem-service/pkg/repository"
	"problem-service/pkg/server"
	"problem-service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeServices(cfg *config.Config) (*server.RpcServer, error) {
	mongoClient, err := db.ConnectToMongo(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(mongoClient)
	userUseCase := usecase.NewUserUseCase(userRepository)
	problemUserClient := client.NewUserClient(userUseCase)
	rpcServer := server.NewRPCServer(cfg, problemUserClient)
	return rpcServer, nil
}
