// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package customerrors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoEmptyValueError-0]
	_ = x[ValidatorError-1]
	_ = x[NoMatchingPasswordError-2]
	_ = x[JwtTokenMissingError-3]
}

const _ErrorCode_name = "NoEmptyValueErrorValidatorErrorNoMatchingPasswordErrorJwtTokenMissingError"

var _ErrorCode_index = [...]uint8{0, 17, 31, 54, 74}

func (i ErrorCode) String() string {
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
